"""Add audit fields to RecommendationAction

Revision ID: a756af4ec22f
Revises: 4ab3a6ad7469
Create Date: 2026-09-01 14:37:52.536424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a756af4ec22f'
down_revision: Union[str, Sequence[str], None] = '4ab3a6ad7469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_actions', sa.Column('previous_status', sa.String(length=50), nullable=True))
    op.add_column('recommendation_actions', sa.Column('new_status', sa.String(length=50), nullable=True))
    op.add_column('recommendation_actions', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_actions', 'notes')
    op.drop_column('recommendation_actions', 'new_status')
    op.drop_column('recommendation_actions', 'previous_status')
    # ### end Alembic commands ###
