import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { recommendationsApi } from '../api/intelligence';
import type { ImpactRecord } from '../types';
import { ProvenancePill } from '../components/ui/ProvenancePill';
import { LoadingState, ErrorState, EmptyState } from '../components/ui/States';

export function ImpactPage() {
  const { recommendationId } = useParams<{ recommendationId: string }>();
  const [impacts, setImpacts] = useState<ImpactRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!recommendationId) return;
    setLoading(true);
    setError(null);
    try {
      const data = await recommendationsApi.getImpact(recommendationId);
      setImpacts(data);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, [recommendationId]);

  useEffect(() => { load(); }, [load]);

  if (!recommendationId) {
    return <EmptyState title="No Action Selected" message="Please select an action from the Action Status page to view its impact." icon="📉" />;
  }

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title">Impact</h1>
          <p className="page-subtitle">Estimated business outcomes from approved actions</p>
        </div>
        <button className="btn btn-secondary" onClick={load} disabled={loading}>
          {loading ? 'Refreshing...' : 'Refresh'}
        </button>
      </div>

      {loading && <LoadingState />}
      {error && <ErrorState error={error} onRetry={load} />}
      {!loading && !error && (
        <>
          <div className="kpi-grid mb-6">
            {impacts.map((imp) => (
              <div className="kpi-tile" key={imp.id}>
                <div className="kpi-label">{imp.metric}</div>
                <div className="kpi-value accent">
                  {imp.metric.includes('Revenue') || imp.metric.includes('Cost') ? '$' : ''}{imp.estimated_value}
                </div>
                <div style={{ marginTop: 8 }}>
                  <ProvenancePill type={imp.is_illustrative ? "ILLUSTRATIVE ESTIMATE" : "REAL"} />
                </div>
              </div>
            ))}
          </div>

          <div className="card">
            <div className="card-header">
              <div>
                <div className="card-title">Impact Records</div>
                <div className="card-subtitle">Action ID: {impacts[0]?.action_id || 'N/A'}</div>
              </div>
            </div>
            <div className="data-table-wrapper">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Metric</th>
                    <th>Estimated Value</th>
                    <th>Actual Value</th>
                    <th>Provenance</th>
                  </tr>
                </thead>
                <tbody>
                  {impacts.map((imp) => (
                    <tr key={imp.id}>
                      <td>{imp.metric}</td>
                      <td style={{ fontWeight: 700, color: 'var(--accent-primary)' }}>
                        {imp.estimated_value}
                      </td>
                      <td style={{ color: 'var(--text-muted)' }}>
                        {imp.actual_value ?? 'Pending'}
                      </td>
                      <td><ProvenancePill type={imp.is_illustrative ? "ILLUSTRATIVE ESTIMATE" : "REAL"} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}

      <div style={{
        marginTop: 20,
        padding: 16,
        background: 'var(--bg-surface)',
        border: '1px solid var(--border-subtle)',
        borderRadius: 'var(--radius-md)',
        fontSize: 12,
        color: 'var(--text-muted)',
        lineHeight: 1.7,
      }}>
        <strong style={{ color: 'var(--provenance-illustrative)', fontSize: 13 }}>
          ILLUSTRATIVE ESTIMATE — Important Disclaimer
        </strong>
        <br />
        Financial figures shown here may be illustrative estimates generated by the system logic to support real measurement when post-action telemetry becomes available. Financial figures are not endorsed by Caterpillar.
      </div>
    </div>
  );
}
