# Allocation Scoring Configuration

# Scoring Weights
SCORE_DEMAND_FIT = 20.0
SCORE_AVAILABLE = 20.0
SCORE_OPERATOR_READY = 10.0

# Penalties and Modifiers
# These are multiplied by the existing utilization/risk scores from Phase 6
UNDERUTILIZATION_MULTIPLIER = 0.5
RISK_PENALTY_MULTIPLIER = 0.5

# Status Thresholds
STATUS_AVAILABLE = "AVAILABLE"
STATUS_RENTED = "RENTED"
STATUS_MAINTENANCE = "MAINTENANCE"

RISK_CRITICAL = "CRITICAL"

# Recommendation States
REC_STATUS_PENDING = "PENDING"
REC_STATUS_APPROVED = "APPROVED"
REC_STATUS_REJECTED = "REJECTED"
REC_STATUS_EXECUTED = "EXECUTED"

# Actions
ACTION_APPROVE = "APPROVE"
ACTION_REJECT = "REJECT"
ACTION_EXECUTE = "EXECUTE"

# Event Types
EVENT_ALLOCATION_EXECUTED = "ALLOCATION_EXECUTED"
